CREATE DATABASE AGGRIGET_FUNCTION
CREATE TABLE SALERY
(FN VARCHAR(20),
LN VARCHAR(20),
DEPARTMENT VARCHAR(20),
SALERY INT);

SELECT*FROM SALERY;

INSERT INTO SALERY VALUES('ROHIT','PATIL','DEVOPMENT',80000);

INSERT INTO SALERY VALUES('JIHAN','SAYYAD','TESTER',90000);

INSERT INTO SALERY VALUES('DIKSHA','SHARMA','BA',100000);

INSERT INTO SALERY VALUES('ANITA','ROY','SM',70000);

INSERT INTO SALERY VALUES('GANESH','SHINDE','DEVOLPER',60000);

INSERT INTO SALERY VALUES('POOJA','SHARMA','ENGINIEER',400000);

INSERT INTO SALERY VALUES('OM','DESHMUKH','CHASHIER',30000);

SELECT*FROM SALERY;

  SELECT MIN(SALERY)FROM SALERY;

  SELECT MAX(SALERY)FROM SALERY;

  SELECT SUM(SALERY)FROM SALERY;

  SELECT AVG(SALERY)FROM SALERY;

  SELECT COUNT(SALERY)FROM SALERY;

  SELECT SUM(SALERY)FROM SALERY GROUP BY SALERY;

  /*TOP MOST VALUES*/
  /*SELECT TOP FIRST SALERT*/
  SELECT MAX(SALERY)FROM SALERY WHERE SALERY NOT IN(SELECT MAX(SALERY)FROM SALERY);

  /*2nd LOWEST VALUES*/

  SELECT MIN(SALERY)FROM SALERY WHERE SALERY NOT IN (SELECT MIN(SALERY)FROM SALERY);

  /*SELECT 3ND HIGHST SALERY*/

  SELECT TOP 1 SALERY FROM(SELECT DISTINCT TOP 3 SALERY FROM SALERY ORDER BY SALERY DESC) RESULT ORDER BY SALERY ASC;

  /*4TH HIGHST SALERY*/
  SELECT MIN(SALERY)FROM SALERY WHERE SALERY IN(SELECT TOP 4 SALERY FROM SALERY ORDER BY SALERY DESC);

  /*5TH HIGHST SALARY*/

  SELECT MIN(SALERY) FROM SALERY WHERE SALERY IN(SELECT TOP 5 SALERY ORDER BY SALERY DESC);