CREATE DATABASE JULYBATCH
CREATE TABLE STUDENTINFORMETION
(FN VARCHAR(30),
LN VARCHAR(30),
MOBILENO INT,
ROLLNO INT);
SELECT * FROM STUDENTINFORMETION;

INSERT INTO STUDENTINFORMETION VALUES('SHABNAM','SAYYAD',12345678,01);

INSERT INTO STUDENTINFORMETION VALUES('KAJAL','FEGADHE',5674839,02);

INSERT INTO STUDENTINFORMETION VALUES('MADHURI','KUPATE',786594356,03);

INSERT INTO STUDENTINFORMETION VALUES('SHIOVAM','MOTHARKAR',456329123,04);

INSERT INTO STUDENTINFORMETION VALUES('NAMRATA','MIRGALE',23457891,05);

INSERT INTO STUDENTINFORMETION VALUES('RAM','ROY',76543281,06);

INSERT INTO STUDENTINFORMETION VALUES('POOJA','PATIL',912367854,07);

SELECT * FROM STUDENTINFORMETION;

SELECT DISTINCT LN FROM STUDENTINFORMETION;

SELECT COUNT(DISTINCT FN) FROM STUDENTINFORMETION;

SELECT TOP 3 * FROM STUDENTINFORMETION;

SELECT TOP 50 PERCENT * FROM STUDENTINFORMETION;

SELECT * FROM STUDENTINFORMETION ORDER BY FN;

SELECT * FROM STUDENTINFORMETION ORDER BY FN DESC;

SELECT * FROM STUDENTINFORMETION WHERE MOBILENO =912367854;

SELECT FN FROM STUDENTINFORMETION WHERE MOBILENO=23457891;

SELECT * FROM STUDENTINFORMETION WHERE FN='SHABNAM'OR LN='SAYYAD';

SELECT MOBILENO FROM STUDENTINFORMETION WHERE FN='RAM' OR LN='ROY';

SELECT * FROM STUDENTINFORMETION WHERE FN='POOJA' AND LN='PATIL';

SELECT FN FROM STUDENTINFORMETION WHERE FN='RAM' AND LN='ROY';

SELECT * FROM STUDENTINFORMETION WHERE FN LIKE 'S%';

SELECT * FROM STUDENTINFORMETION WHERE FN LIKE '%M';

SELECT * FROM STUDENTINFORMETION WHERE FN NOT LIKE 'S%';

SELECT * FROM STUDENTINFORMETION WHERE FN IN('SHABNAM','RAM','POOJA','KAJAL');

SELECT * FROM STUDENTINFORMETION WHERE FN NOT IN('SHABNAM','RAM');

SELECT * FROM STUDENTINFORMETION WHERE ROLLNO BETWEEN 2 AND 4;

SELECT * FROM STUDENTINFORMETION WHERE ROLLNO NOT BETWEEN 2 AND 4;

UPDATE STUDENTINFORMETION SET MOBILENO =12345678 WHERE FN='SHABNAM';

DELETE FROM STUDENTINFORMETION WHERE MOBILENO=12345678;

DELETE FROM STUDENTINFORMETION;

CREATE TABLE STUDENTINFORMETION2
(FN VARCHAR (30),
LN VARCHAR(30),
MOBILENO INT,
ROLLNO INT)

SELECT * FROM STUDENTINFORMETION2;

INSERT INTO STUDENTINFORMETION2 VALUES('SHABNAM','SAYYAD',12345678,01);

INSERT INTO STUDENTINFORMETION2 VALUES('KAJAL','FEGADHE',5674839,02);

INSERT INTO STUDENTINFORMETION2 VALUES('MADHURI','KUPATE',786594356,03);

INSERT INTO STUDENTINFORMETION2 VALUES('SHIOVAM','MOTHARKAR',456329123,04);

INSERT INTO STUDENTINFORMETION2 VALUES('NAMRATA','MIRGALE',23457891,05);

INSERT INTO STUDENTINFORMETION2 VALUES('RAM','ROY',76543281,06);

INSERT INTO STUDENTINFORMETION2 VALUES('POOJA','PATIL',912367854,07);

SELECT * FROM STUDENTINFORMETION2;

SELECT *INTO STUDENTINFORMETI01 FROM STUDENTINFORMETION;

SELECT FN AS FIRSTNAME,LN AS LASTNAME FROM STUDENTINFORMETION;   /*ALIAS */

SELECT FN FROM STUDENTINFORMETION UNION SELECT LN FROM STUDENTINFORMETION1; /*UNION */

SELECT FN FROM STUDENTINFORMETION UNION ALL SELECT LN FROM STUDENTINFORMETION1; /*UNION ALL */

/*CONSTRAINTS*/

CREATE TABLE VELOCITY1
(SRNO INT PRIMARY KEY,
FN VARCHAR(30),
LN VARCHAR(30),
MOCKRESULT INT ,
LOCARION VARCHAR(30),
MOBILENO INT);

SELECT * FROM VELOCITY1;

INSERT INTO VELOCITY1 VALUES(1,'OM','PATIL',25,'PUNE',1234567890);

INSERT INTO VELOCITY1 VALUES(2,'JIHAN','SAYYAD',23,'NAGER',2314567890);

INSERT INTO VELOCITY1 VALUES(3,'AKIL','SAYYAD',27,'NEWASA',4563217890);

INSERT INTO VELOCITY1 VALUES(4,'RAHUL','ROY',24,'NASHIK',9087654321);

INSERT INTO VELOCITY1 VALUES(5,'ROHIT','DESHMUKH',25,'SHRIRAMPUR',9123456780);

SELECT * FROM VELOCITY1;

/*NOTNULL*/

CREATE TABLE RAGISTR
(ID INT NOT NULL,
FN VARCHAR(30) NOT NULL,
LN VARCHAR(30) NOT NULL,
MOBNO INT NOT NULL,
EMAILID VARCHAR(30)NOT NULL,
CITY VARCHAR(30) NOT NULL);

/*UNIQUE KEY*/
CREATE TABLE SOFTWERTESTING
(ID INT NOT NULL,
FN VARCHAR(30) NOT NULL,
LN VARCHAR(30) NOT NULL,
MOBNO INT NOT NULL UNIQUE,
EMAILID VARCHAR(30)NOT NULL,
CITY VARCHAR(30) NOT NULL);

/*JOIN*/

CREATE TABLE STUDENTINFO2
(FN VARCHAR(20),
LN VARCHAR(30),
CITY VARCHAR(30),
MOBILENO INT,
PRIMARY KEY(MOBILENO));

SELECT * FROM STUDENTINFO2;

INSERT INTO STUDENTINFO2 VALUES('OM','ROY','PUNE',1234);

INSERT INTO STUDENTINFO2 VALUES('RAHUL','PATIL','NEWASA',12345);

INSERT INTO STUDENTINFO2 VALUES('JIHAN','SAYYAD','NAGER',54321);

INSERT INTO STUDENTINFO2 VALUES('ROHIT','SHARMA','MUMBAI',123456);

SELECT * FROM STUDENTINFO2;
 
CREATE TABLE FEES1
(MOBILENO INT,
FIRSTINST INT,
SECONDINST INT,
FOREIGN KEY(MOBILENO) REFERENCES STUDENTINFO2(MOBILENO)
);

SELECT *FROM FEES1;

INSERT INTO FEES1 VALUES(1234,10000,20000);

INSERT INTO FEES1 VALUES(12345,10000,30000);

INSERT INTO FEES1 VALUES(123456,30000,20000);

INSERT INTO FEES1 VALUES(54321,20000,10000);

INSERT INTO FEES1 VALUES(12345,1000,20000);

SELECT * FROM FEES1;

/*INNER JOIN*/

SELECT STUDENTINFO2.FN,
       STUDENTINFO2.LN,
	   FEES1.FIRSTINST,
	   FEES1.SECONDINST FROM STUDENTINFO2 INNER JOIN FEES1
	   ON STUDENTINFO2.MOBILENO=FEES1.MOBILENO;

	   /*LEFT JOIN*/

	   
SELECT STUDENTINFO2.FN,
       STUDENTINFO2.LN,
	   FEES1.FIRSTINST,
	   FEES1.SECONDINST FROM STUDENTINFO2 LEFT JOIN FEES1
	   ON STUDENTINFO2.MOBILENO=FEES1.MOBILENO;

	   /*RIGHT JOIN*/
	   
SELECT STUDENTINFO2.FN,
       STUDENTINFO2.LN,
	   FEES1.FIRSTINST,
	   FEES1.SECONDINST FROM STUDENTINFO2 RIGHT JOIN FEES1
	   ON STUDENTINFO2.MOBILENO=FEES1.MOBILENO;

	   /*FULL JOIN*/
	   
SELECT STUDENTINFO2.FN,
       STUDENTINFO2.LN,
	   FEES1.FIRSTINST,
	   FEES1.SECONDINST FROM STUDENTINFO2 FULL JOIN FEES1
	   ON STUDENTINFO2.MOBILENO=FEES1.MOBILENO;
























  

     